interface ZIF_BO_MGULLA_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0050568CF1B11EDAB690D76A19E640EE' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZBO_MGULLA' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '0050568CF1B11EDAB690D76A19E700EE',
    END OF SC_NODE .
endinterface.
